services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  shipyard-api:
    image: rishabhchaudhary0210/shipyard-api:latest
    command: npm run start:api
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      DOCKER_SOCKET_PATH: /var/run/docker.sock
      PORT: 8000
      SHIPYARD_WORKSPACE_ROOT: /shipyard-workspace
      SHIPYARD_WORKSPACE_HOST_ROOT: ${SHIPYARD_WORKSPACE_HOST_ROOT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shipyard-workspace:/shipyard-workspace
    depends_on:
      - redis

  shipyard-worker:
    image: rishabhchaudhary0210/shipyard-api:latest
    command: npm run start:worker
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      DOCKER_SOCKET_PATH: /var/run/docker.sock
      SHIPYARD_WORKSPACE_ROOT: /shipyard-workspace
      SHIPYARD_WORKSPACE_HOST_ROOT: ${SHIPYARD_WORKSPACE_HOST_ROOT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shipyard-workspace:/shipyard-workspace
    depends_on:
      - redis
    
  
